language: node_js
node_js:
  - "10"
os: linux
arch: arm64
dist: xenial
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install
  - gulp testSupport
stages:
  - name: test
jobs:
  include:
    - stage: test
      script:
        - cd clients
        - yarn install
        - yarn test
